services:
  config-service:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    image: config-service
    volumes:
      - ./config-server-data:/data/config-server-data
    ports:
     - 9999:9999

  registry-service:
    depends_on:
      - config-service
    build:
      context: ./registry
      dockerfile: Dockerfile
    image: registry-service
    ports:
      - 8761:8761
    environment:
      PROFILE: dev
      CONFIGSERVER_URI: config-service:9999
      CONFIGSERVER_PORT: 9999

  order-service:
    depends_on: [config-service,registry-service]
    image: order-service
    build:
      context: ./order
      dockerfile: Dockerfile
    ports:
      - 8334:8334
    environment:
      PROFILE: dev
      CONFIGSERVER_URI: config-service:9999

  inventory-service:
    depends_on: [ config-service,registry-service ]
    image: inventory-service
    build:
      context: ./inventory
      dockerfile: Dockerfile
    ports:
      - 8340:8340
    environment:
      PROFILE: dev
      CONFIGSERVER_URI: config-service:9999

  database:
    image: postgres:16.1-alpine3.19
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p0stgr@s
      - POSTGRES_DB=project_x_local