### get v1 api
GET http://localhost:8080/v1/api/inventory/53e500be-6730-4afb-a0d2-3c7abf980de3

### get v1 api inventory
GET http://localhost:8080/v1/api/inventory/

### craete new inventory
POST http://localhost:8080/v1/api/inventory/
Content-Type: application/json

{"name":"s23","quantity":"300","price": "300"}